TrainingMVC/Controllers/LoginController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrainingMVC.Dtos;
using Microsoft.AspNetCore.Http;
using NToastNotify;
using MediatR;
using TrainingMVC.Query.User;

namespace TrainingMVC.Controllers
{
    public class LoginController : Controller
    {
        private IMediator _mediator;
        private IToastNotification _toastNotification;
        public LoginController(IToastNotification toastNotification, IMediator mediator)
        {
            _toastNotification = toastNotification;
            _mediator = mediator;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserDto userDto)
        {
            if (ModelState.IsValid)
            {
                var login = await _mediator.Send(new AuthenUserQuery(userDto));
                if (!login)
                {
                    //ModelState.AddModelError("", "The User name or password is incorrect");
                    _toastNotification.AddErrorToastMessage("The User name or password is incorrect");
                    return View();
                }
                HttpContext.Session.SetString("username", userDto.UserName);
                return RedirectToAction("Index", "Book");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToRoute(new
            {
                controller = "Book",
                action = "Index"
            });
        }
    }
}

TrainingMVC/Views/Login/Login.cshtml
@model TrainingMVC.Dtos.UserDto
<div class="container">

    <div class="row">
        <div class="col s12">
            <h1 class="center-align grey-text text-darken-4">Login</h1>
        </div>
    </div>

    <br />
    <br />
    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <form id="insertForm" asp-controller="Login" asp-action="Login"
                          method="post">
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons iconis prefix">account_box</i>
                                <input asp-for="@Model.UserName">
                                @Html.LabelFor(m => m.UserName)
                                @*<label for="UserName">User Name</label>*@
                                <span asp-validation-for="@Model.UserName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons iconis prefix">enhanced_encryption</i>
                                <input asp-for="@Model.Password">
                                @Html.LabelFor(m => m.Password)
                                @*<label for="Password">Password</label>*@
                                <span asp-validation-for="@Model.Password" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s12 center-align">
                                <button class="btn waves-effect red lighten-1" type="submit" name="action">
                                    Submit
                                    <i class="material-icons right">send</i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>